# Generated by Django 6.0.2 on 2026-03-19 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tuttiuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrobble',
            name='user_id',
        ),
        migrations.AddField(
            model_name='scrobble',
            name='tuttiuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
