# Generated by Django 6.0.2 on 2026-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_scrobble_user_id_scrobble_tuttiuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrobble',
            old_name='musicbrainz_id',
            new_name='recording_mbid',
        ),
        migrations.AddField(
            model_name='scrobble',
            name='release_mbid',
            field=models.CharField(default='1', max_length=36),
            preserve_default=False,
        ),
    ]
