# Generated by Django 6.0.2 on 2026-03-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_musicbrainz_id_scrobble_recording_mbid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('data', models.CharField()),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
