# Generated by Django 6.0.2 on 2026-03-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cachedquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrobble',
            name='recording_mbid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='release_mbid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
