# Generated by Django 6.0.2 on 2026-03-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_scrobble_recording_mbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrobble',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='recording_mbid',
            field=models.CharField(default='1', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='release_mbid',
            field=models.CharField(default='1', max_length=36),
            preserve_default=False,
        ),
    ]
