# Generated by Django 6.0.2 on 2026-04-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scrobble_rating_alter_scrobble_recording_mbid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_mbid', models.CharField(max_length=36)),
                ('recording_mbid', models.CharField(max_length=36)),
            ],
        ),
        migrations.RemoveField(
            model_name='scrobble',
            name='recording_mbid',
        ),
        migrations.RemoveField(
            model_name='scrobble',
            name='release_mbid',
        ),
        migrations.AddField(
            model_name='scrobble',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.song'),
            preserve_default=False,
        ),
    ]
