# Generated by Django 6.0.2 on 2026-04-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recommendation_recommendationreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuttiuser',
            name='city',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tuttiuser',
            name='country',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tuttiuser',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
