# Generated by Django 6.0.2 on 2026-04-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tuttiuser_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='api.song'),
        ),
    ]
