# Generated by Django 6.0.2 on 2026-04-13 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_recommendation_recommended_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationreaction',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='recommendationreaction',
            name='tuttiuser',
        ),
        migrations.AddField(
            model_name='song',
            name='recommendations',
            field=models.ManyToManyField(to='api.song'),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobbles', to='api.song'),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='tuttiuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobbles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='RecommendationReaction',
        ),
    ]
