# Generated by Django 6.0.2 on 2026-04-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_recommendationreaction_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='recommendations',
            field=models.ManyToManyField(related_name='recommended_by', to='api.song'),
        ),
    ]
