# Generated by Django 6.0.2 on 2026-04-13 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_song_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='recommendations',
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('base_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.song')),
                ('recommended_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.song')),
                ('tuttiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.recommendation')),
                ('tuttiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
