# Generated by Django 6.0.2 on 2026-04-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_recommendation_recommended_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationreaction',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='recommendationreaction',
            name='tuttiuser',
        ),
        migrations.AddField(
            model_name='song',
            name='recommendations',
            field=models.ManyToManyField(related_name='recommended_by', to='api.song'),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='RecommendationReaction',
        ),
    ]
