# Generated by Django 6.0.2 on 2026-04-13 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_recommendationreaction_recommendation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='recommendations',
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('base_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.song')),
                ('recommended_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='api.song')),
                ('tuttiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
